/*
 * This file is generated by jOOQ.
 */
package Repositories.jooqGenEntities.tables.records;


import Repositories.jooqGenEntities.tables.InCurrentReading;

import java.beans.ConstructorProperties;

import javax.annotation.processing.Generated;

import org.jetbrains.annotations.NotNull;
import org.jooq.Field;
import org.jooq.Record2;
import org.jooq.Row2;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.18.13"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class InCurrentReadingRecord extends UpdatableRecordImpl<InCurrentReadingRecord> implements Record2<Long, Long> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.in_current_reading.manga_id</code>.
     */
    public void setMangaId(@NotNull Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.in_current_reading.manga_id</code>.
     */
    @jakarta.validation.constraints.NotNull
    @NotNull
    public Long getMangaId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>public.in_current_reading.user_id</code>.
     */
    public void setUserId(@NotNull Long value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.in_current_reading.user_id</code>.
     */
    @jakarta.validation.constraints.NotNull
    @NotNull
    public Long getUserId() {
        return (Long) get(1);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    @NotNull
    public Record2<Long, Long> key() {
        return (Record2) super.key();
    }

    // -------------------------------------------------------------------------
    // Record2 type implementation
    // -------------------------------------------------------------------------

    @Override
    @NotNull
    public Row2<Long, Long> fieldsRow() {
        return (Row2) super.fieldsRow();
    }

    @Override
    @NotNull
    public Row2<Long, Long> valuesRow() {
        return (Row2) super.valuesRow();
    }

    @Override
    @NotNull
    public Field<Long> field1() {
        return InCurrentReading.IN_CURRENT_READING.MANGA_ID;
    }

    @Override
    @NotNull
    public Field<Long> field2() {
        return InCurrentReading.IN_CURRENT_READING.USER_ID;
    }

    @Override
    @NotNull
    public Long component1() {
        return getMangaId();
    }

    @Override
    @NotNull
    public Long component2() {
        return getUserId();
    }

    @Override
    @NotNull
    public Long value1() {
        return getMangaId();
    }

    @Override
    @NotNull
    public Long value2() {
        return getUserId();
    }

    @Override
    @NotNull
    public InCurrentReadingRecord value1(@NotNull Long value) {
        setMangaId(value);
        return this;
    }

    @Override
    @NotNull
    public InCurrentReadingRecord value2(@NotNull Long value) {
        setUserId(value);
        return this;
    }

    @Override
    @NotNull
    public InCurrentReadingRecord values(@NotNull Long value1, @NotNull Long value2) {
        value1(value1);
        value2(value2);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached InCurrentReadingRecord
     */
    public InCurrentReadingRecord() {
        super(InCurrentReading.IN_CURRENT_READING);
    }

    /**
     * Create a detached, initialised InCurrentReadingRecord
     */
    @ConstructorProperties({ "mangaId", "userId" })
    public InCurrentReadingRecord(@NotNull Long mangaId, @NotNull Long userId) {
        super(InCurrentReading.IN_CURRENT_READING);

        setMangaId(mangaId);
        setUserId(userId);
        resetChangedOnNotNull();
    }

    /**
     * Create a detached, initialised InCurrentReadingRecord
     */
    public InCurrentReadingRecord(Repositories.jooqGenEntities.tables.pojos.InCurrentReading value) {
        super(InCurrentReading.IN_CURRENT_READING);

        if (value != null) {
            setMangaId(value.getMangaId());
            setUserId(value.getUserId());
            resetChangedOnNotNull();
        }
    }
}
