/*
 * This file is generated by jOOQ.
 */
package Repositories.jooqGenEntities.tables.records;


import Repositories.jooqGenEntities.tables.MangaTypeTag;

import java.beans.ConstructorProperties;

import javax.annotation.processing.Generated;

import org.jetbrains.annotations.NotNull;
import org.jetbrains.annotations.Nullable;
import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record3;
import org.jooq.Row3;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.18.13"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class MangaTypeTagRecord extends UpdatableRecordImpl<MangaTypeTagRecord> implements Record3<String, String, Long> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.manga_type_tag.tag</code>.
     */
    public void setTag(@Nullable String value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.manga_type_tag.tag</code>.
     */
    @Nullable
    public String getTag() {
        return (String) get(0);
    }

    /**
     * Setter for <code>public.manga_type_tag._type</code>.
     */
    public void set_Type(@Nullable String value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.manga_type_tag._type</code>.
     */
    @Nullable
    public String get_Type() {
        return (String) get(1);
    }

    /**
     * Setter for <code>public.manga_type_tag.manga_id</code>.
     */
    public void setMangaId(@NotNull Long value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.manga_type_tag.manga_id</code>.
     */
    @jakarta.validation.constraints.NotNull
    @NotNull
    public Long getMangaId() {
        return (Long) get(2);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    @NotNull
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record3 type implementation
    // -------------------------------------------------------------------------

    @Override
    @NotNull
    public Row3<String, String, Long> fieldsRow() {
        return (Row3) super.fieldsRow();
    }

    @Override
    @NotNull
    public Row3<String, String, Long> valuesRow() {
        return (Row3) super.valuesRow();
    }

    @Override
    @NotNull
    public Field<String> field1() {
        return MangaTypeTag.MANGA_TYPE_TAG.TAG;
    }

    @Override
    @NotNull
    public Field<String> field2() {
        return MangaTypeTag.MANGA_TYPE_TAG._TYPE;
    }

    @Override
    @NotNull
    public Field<Long> field3() {
        return MangaTypeTag.MANGA_TYPE_TAG.MANGA_ID;
    }

    @Override
    @Nullable
    public String component1() {
        return getTag();
    }

    @Override
    @Nullable
    public String component2() {
        return get_Type();
    }

    @Override
    @NotNull
    public Long component3() {
        return getMangaId();
    }

    @Override
    @Nullable
    public String value1() {
        return getTag();
    }

    @Override
    @Nullable
    public String value2() {
        return get_Type();
    }

    @Override
    @NotNull
    public Long value3() {
        return getMangaId();
    }

    @Override
    @NotNull
    public MangaTypeTagRecord value1(@Nullable String value) {
        setTag(value);
        return this;
    }

    @Override
    @NotNull
    public MangaTypeTagRecord value2(@Nullable String value) {
        set_Type(value);
        return this;
    }

    @Override
    @NotNull
    public MangaTypeTagRecord value3(@NotNull Long value) {
        setMangaId(value);
        return this;
    }

    @Override
    @NotNull
    public MangaTypeTagRecord values(@Nullable String value1, @Nullable String value2, @NotNull Long value3) {
        value1(value1);
        value2(value2);
        value3(value3);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached MangaTypeTagRecord
     */
    public MangaTypeTagRecord() {
        super(MangaTypeTag.MANGA_TYPE_TAG);
    }

    /**
     * Create a detached, initialised MangaTypeTagRecord
     */
    @ConstructorProperties({ "tag", "_Type", "mangaId" })
    public MangaTypeTagRecord(@Nullable String tag, @Nullable String _Type, @NotNull Long mangaId) {
        super(MangaTypeTag.MANGA_TYPE_TAG);

        setTag(tag);
        set_Type(_Type);
        setMangaId(mangaId);
        resetChangedOnNotNull();
    }

    /**
     * Create a detached, initialised MangaTypeTagRecord
     */
    public MangaTypeTagRecord(Repositories.jooqGenEntities.tables.pojos.MangaTypeTag value) {
        super(MangaTypeTag.MANGA_TYPE_TAG);

        if (value != null) {
            setTag(value.getTag());
            set_Type(value.get_Type());
            setMangaId(value.getMangaId());
            resetChangedOnNotNull();
        }
    }
}
