/*
 * This file is generated by jOOQ.
 */
package Repositories.jooqGenEntities.tables.records;


import Repositories.jooqGenEntities.tables.Recommendation;

import java.beans.ConstructorProperties;

import javax.annotation.processing.Generated;

import org.jetbrains.annotations.NotNull;
import org.jetbrains.annotations.Nullable;
import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record3;
import org.jooq.Row3;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.18.13"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class RecommendationRecord extends UpdatableRecordImpl<RecommendationRecord> implements Record3<Long, Long, Long> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.recommendation.recommendate_id</code>.
     */
    public void setRecommendateId(@Nullable Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.recommendation.recommendate_id</code>.
     */
    @Nullable
    public Long getRecommendateId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>public.recommendation.manga_id</code>.
     */
    public void setMangaId(@Nullable Long value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.recommendation.manga_id</code>.
     */
    @Nullable
    public Long getMangaId() {
        return (Long) get(1);
    }

    /**
     * Setter for <code>public.recommendation.user_id</code>.
     */
    public void setUserId(@Nullable Long value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.recommendation.user_id</code>.
     */
    @Nullable
    public Long getUserId() {
        return (Long) get(2);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    @NotNull
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record3 type implementation
    // -------------------------------------------------------------------------

    @Override
    @NotNull
    public Row3<Long, Long, Long> fieldsRow() {
        return (Row3) super.fieldsRow();
    }

    @Override
    @NotNull
    public Row3<Long, Long, Long> valuesRow() {
        return (Row3) super.valuesRow();
    }

    @Override
    @NotNull
    public Field<Long> field1() {
        return Recommendation.RECOMMENDATION.RECOMMENDATE_ID;
    }

    @Override
    @NotNull
    public Field<Long> field2() {
        return Recommendation.RECOMMENDATION.MANGA_ID;
    }

    @Override
    @NotNull
    public Field<Long> field3() {
        return Recommendation.RECOMMENDATION.USER_ID;
    }

    @Override
    @Nullable
    public Long component1() {
        return getRecommendateId();
    }

    @Override
    @Nullable
    public Long component2() {
        return getMangaId();
    }

    @Override
    @Nullable
    public Long component3() {
        return getUserId();
    }

    @Override
    @Nullable
    public Long value1() {
        return getRecommendateId();
    }

    @Override
    @Nullable
    public Long value2() {
        return getMangaId();
    }

    @Override
    @Nullable
    public Long value3() {
        return getUserId();
    }

    @Override
    @NotNull
    public RecommendationRecord value1(@Nullable Long value) {
        setRecommendateId(value);
        return this;
    }

    @Override
    @NotNull
    public RecommendationRecord value2(@Nullable Long value) {
        setMangaId(value);
        return this;
    }

    @Override
    @NotNull
    public RecommendationRecord value3(@Nullable Long value) {
        setUserId(value);
        return this;
    }

    @Override
    @NotNull
    public RecommendationRecord values(@Nullable Long value1, @Nullable Long value2, @Nullable Long value3) {
        value1(value1);
        value2(value2);
        value3(value3);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached RecommendationRecord
     */
    public RecommendationRecord() {
        super(Recommendation.RECOMMENDATION);
    }

    /**
     * Create a detached, initialised RecommendationRecord
     */
    @ConstructorProperties({ "recommendateId", "mangaId", "userId" })
    public RecommendationRecord(@Nullable Long recommendateId, @Nullable Long mangaId, @Nullable Long userId) {
        super(Recommendation.RECOMMENDATION);

        setRecommendateId(recommendateId);
        setMangaId(mangaId);
        setUserId(userId);
        resetChangedOnNotNull();
    }

    /**
     * Create a detached, initialised RecommendationRecord
     */
    public RecommendationRecord(Repositories.jooqGenEntities.tables.pojos.Recommendation value) {
        super(Recommendation.RECOMMENDATION);

        if (value != null) {
            setRecommendateId(value.getRecommendateId());
            setMangaId(value.getMangaId());
            setUserId(value.getUserId());
            resetChangedOnNotNull();
        }
    }
}
