/*
 * This file is generated by jOOQ.
 */
package Repositories.jooqGenEntities.tables.records;


import Repositories.jooqGenEntities.tables.Reviews;

import java.beans.ConstructorProperties;

import javax.annotation.processing.Generated;

import org.jetbrains.annotations.NotNull;
import org.jetbrains.annotations.Nullable;
import org.jooq.Field;
import org.jooq.Record2;
import org.jooq.Record3;
import org.jooq.Row3;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.18.13"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ReviewsRecord extends UpdatableRecordImpl<ReviewsRecord> implements Record3<Long, Long, Integer> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.reviews.manga_id</code>.
     */
    public void setMangaId(@NotNull Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.reviews.manga_id</code>.
     */
    @jakarta.validation.constraints.NotNull
    @NotNull
    public Long getMangaId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>public.reviews.user_id</code>.
     */
    public void setUserId(@NotNull Long value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.reviews.user_id</code>.
     */
    @jakarta.validation.constraints.NotNull
    @NotNull
    public Long getUserId() {
        return (Long) get(1);
    }

    /**
     * Setter for <code>public.reviews.review_rate</code>.
     */
    public void setReviewRate(@Nullable Integer value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.reviews.review_rate</code>.
     */
    @Nullable
    public Integer getReviewRate() {
        return (Integer) get(2);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    @NotNull
    public Record2<Long, Long> key() {
        return (Record2) super.key();
    }

    // -------------------------------------------------------------------------
    // Record3 type implementation
    // -------------------------------------------------------------------------

    @Override
    @NotNull
    public Row3<Long, Long, Integer> fieldsRow() {
        return (Row3) super.fieldsRow();
    }

    @Override
    @NotNull
    public Row3<Long, Long, Integer> valuesRow() {
        return (Row3) super.valuesRow();
    }

    @Override
    @NotNull
    public Field<Long> field1() {
        return Reviews.REVIEWS.MANGA_ID;
    }

    @Override
    @NotNull
    public Field<Long> field2() {
        return Reviews.REVIEWS.USER_ID;
    }

    @Override
    @NotNull
    public Field<Integer> field3() {
        return Reviews.REVIEWS.REVIEW_RATE;
    }

    @Override
    @NotNull
    public Long component1() {
        return getMangaId();
    }

    @Override
    @NotNull
    public Long component2() {
        return getUserId();
    }

    @Override
    @Nullable
    public Integer component3() {
        return getReviewRate();
    }

    @Override
    @NotNull
    public Long value1() {
        return getMangaId();
    }

    @Override
    @NotNull
    public Long value2() {
        return getUserId();
    }

    @Override
    @Nullable
    public Integer value3() {
        return getReviewRate();
    }

    @Override
    @NotNull
    public ReviewsRecord value1(@NotNull Long value) {
        setMangaId(value);
        return this;
    }

    @Override
    @NotNull
    public ReviewsRecord value2(@NotNull Long value) {
        setUserId(value);
        return this;
    }

    @Override
    @NotNull
    public ReviewsRecord value3(@Nullable Integer value) {
        setReviewRate(value);
        return this;
    }

    @Override
    @NotNull
    public ReviewsRecord values(@NotNull Long value1, @NotNull Long value2, @Nullable Integer value3) {
        value1(value1);
        value2(value2);
        value3(value3);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ReviewsRecord
     */
    public ReviewsRecord() {
        super(Reviews.REVIEWS);
    }

    /**
     * Create a detached, initialised ReviewsRecord
     */
    @ConstructorProperties({ "mangaId", "userId", "reviewRate" })
    public ReviewsRecord(@NotNull Long mangaId, @NotNull Long userId, @Nullable Integer reviewRate) {
        super(Reviews.REVIEWS);

        setMangaId(mangaId);
        setUserId(userId);
        setReviewRate(reviewRate);
        resetChangedOnNotNull();
    }

    /**
     * Create a detached, initialised ReviewsRecord
     */
    public ReviewsRecord(Repositories.jooqGenEntities.tables.pojos.Reviews value) {
        super(Reviews.REVIEWS);

        if (value != null) {
            setMangaId(value.getMangaId());
            setUserId(value.getUserId());
            setReviewRate(value.getReviewRate());
            resetChangedOnNotNull();
        }
    }
}
