/*
 * This file is generated by jOOQ.
 */
package Repositories.jooqGenEntities.tables.records;


import Repositories.jooqGenEntities.tables.Translator;

import java.beans.ConstructorProperties;

import javax.annotation.processing.Generated;

import org.jetbrains.annotations.NotNull;
import org.jetbrains.annotations.Nullable;
import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record2;
import org.jooq.Row2;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.18.13"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TranslatorRecord extends UpdatableRecordImpl<TranslatorRecord> implements Record2<Long, String> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.translator.translator_id</code>.
     */
    public void setTranslatorId(@Nullable Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.translator.translator_id</code>.
     */
    @Nullable
    public Long getTranslatorId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>public.translator.translator_name</code>.
     */
    public void setTranslatorName(@Nullable String value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.translator.translator_name</code>.
     */
    @Nullable
    public String getTranslatorName() {
        return (String) get(1);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    @NotNull
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record2 type implementation
    // -------------------------------------------------------------------------

    @Override
    @NotNull
    public Row2<Long, String> fieldsRow() {
        return (Row2) super.fieldsRow();
    }

    @Override
    @NotNull
    public Row2<Long, String> valuesRow() {
        return (Row2) super.valuesRow();
    }

    @Override
    @NotNull
    public Field<Long> field1() {
        return Translator.TRANSLATOR.TRANSLATOR_ID;
    }

    @Override
    @NotNull
    public Field<String> field2() {
        return Translator.TRANSLATOR.TRANSLATOR_NAME;
    }

    @Override
    @Nullable
    public Long component1() {
        return getTranslatorId();
    }

    @Override
    @Nullable
    public String component2() {
        return getTranslatorName();
    }

    @Override
    @Nullable
    public Long value1() {
        return getTranslatorId();
    }

    @Override
    @Nullable
    public String value2() {
        return getTranslatorName();
    }

    @Override
    @NotNull
    public TranslatorRecord value1(@Nullable Long value) {
        setTranslatorId(value);
        return this;
    }

    @Override
    @NotNull
    public TranslatorRecord value2(@Nullable String value) {
        setTranslatorName(value);
        return this;
    }

    @Override
    @NotNull
    public TranslatorRecord values(@Nullable Long value1, @Nullable String value2) {
        value1(value1);
        value2(value2);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached TranslatorRecord
     */
    public TranslatorRecord() {
        super(Translator.TRANSLATOR);
    }

    /**
     * Create a detached, initialised TranslatorRecord
     */
    @ConstructorProperties({ "translatorId", "translatorName" })
    public TranslatorRecord(@Nullable Long translatorId, @Nullable String translatorName) {
        super(Translator.TRANSLATOR);

        setTranslatorId(translatorId);
        setTranslatorName(translatorName);
        resetChangedOnNotNull();
    }

    /**
     * Create a detached, initialised TranslatorRecord
     */
    public TranslatorRecord(Repositories.jooqGenEntities.tables.pojos.Translator value) {
        super(Translator.TRANSLATOR);

        if (value != null) {
            setTranslatorId(value.getTranslatorId());
            setTranslatorName(value.getTranslatorName());
            resetChangedOnNotNull();
        }
    }
}
