/*
 * This file is generated by jOOQ.
 */
package Repositories.jooqGenEntities.tables.pojos;


import jakarta.validation.constraints.Size;

import java.beans.ConstructorProperties;
import java.io.Serializable;

import javax.annotation.processing.Generated;

import org.jetbrains.annotations.Nullable;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.18.13"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Commentary implements Serializable {

    private static final long serialVersionUID = 1L;

    private Long commentaryId;
    private String commentary;
    private Long mangaId;
    private Long userId;

    public Commentary() {}

    public Commentary(Commentary value) {
        this.commentaryId = value.commentaryId;
        this.commentary = value.commentary;
        this.mangaId = value.mangaId;
        this.userId = value.userId;
    }

    @ConstructorProperties({ "commentaryId", "commentary", "mangaId", "userId" })
    public Commentary(
        @Nullable Long commentaryId,
        @Nullable String commentary,
        @Nullable Long mangaId,
        @Nullable Long userId
    ) {
        this.commentaryId = commentaryId;
        this.commentary = commentary;
        this.mangaId = mangaId;
        this.userId = userId;
    }

    /**
     * Getter for <code>public.commentary.commentary_id</code>.
     */
    @Nullable
    public Long getCommentaryId() {
        return this.commentaryId;
    }

    /**
     * Setter for <code>public.commentary.commentary_id</code>.
     */
    public void setCommentaryId(@Nullable Long commentaryId) {
        this.commentaryId = commentaryId;
    }

    /**
     * Getter for <code>public.commentary.commentary</code>.
     */
    @Size(max = 255)
    @Nullable
    public String getCommentary() {
        return this.commentary;
    }

    /**
     * Setter for <code>public.commentary.commentary</code>.
     */
    public void setCommentary(@Nullable String commentary) {
        this.commentary = commentary;
    }

    /**
     * Getter for <code>public.commentary.manga_id</code>.
     */
    @Nullable
    public Long getMangaId() {
        return this.mangaId;
    }

    /**
     * Setter for <code>public.commentary.manga_id</code>.
     */
    public void setMangaId(@Nullable Long mangaId) {
        this.mangaId = mangaId;
    }

    /**
     * Getter for <code>public.commentary.user_id</code>.
     */
    @Nullable
    public Long getUserId() {
        return this.userId;
    }

    /**
     * Setter for <code>public.commentary.user_id</code>.
     */
    public void setUserId(@Nullable Long userId) {
        this.userId = userId;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final Commentary other = (Commentary) obj;
        if (this.commentaryId == null) {
            if (other.commentaryId != null)
                return false;
        }
        else if (!this.commentaryId.equals(other.commentaryId))
            return false;
        if (this.commentary == null) {
            if (other.commentary != null)
                return false;
        }
        else if (!this.commentary.equals(other.commentary))
            return false;
        if (this.mangaId == null) {
            if (other.mangaId != null)
                return false;
        }
        else if (!this.mangaId.equals(other.mangaId))
            return false;
        if (this.userId == null) {
            if (other.userId != null)
                return false;
        }
        else if (!this.userId.equals(other.userId))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.commentaryId == null) ? 0 : this.commentaryId.hashCode());
        result = prime * result + ((this.commentary == null) ? 0 : this.commentary.hashCode());
        result = prime * result + ((this.mangaId == null) ? 0 : this.mangaId.hashCode());
        result = prime * result + ((this.userId == null) ? 0 : this.userId.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Commentary (");

        sb.append(commentaryId);
        sb.append(", ").append(commentary);
        sb.append(", ").append(mangaId);
        sb.append(", ").append(userId);

        sb.append(")");
        return sb.toString();
    }
}
