/*
 * This file is generated by jOOQ.
 */
package Repositories.jooqGenEntities.tables.pojos;


import java.beans.ConstructorProperties;
import java.io.Serializable;

import javax.annotation.processing.Generated;

import org.jetbrains.annotations.NotNull;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.18.13"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class InCurrentReading implements Serializable {

    private static final long serialVersionUID = 1L;

    private Long mangaId;
    private Long userId;

    public InCurrentReading() {}

    public InCurrentReading(InCurrentReading value) {
        this.mangaId = value.mangaId;
        this.userId = value.userId;
    }

    @ConstructorProperties({ "mangaId", "userId" })
    public InCurrentReading(
        @NotNull Long mangaId,
        @NotNull Long userId
    ) {
        this.mangaId = mangaId;
        this.userId = userId;
    }

    /**
     * Getter for <code>public.in_current_reading.manga_id</code>.
     */
    @jakarta.validation.constraints.NotNull
    @NotNull
    public Long getMangaId() {
        return this.mangaId;
    }

    /**
     * Setter for <code>public.in_current_reading.manga_id</code>.
     */
    public void setMangaId(@NotNull Long mangaId) {
        this.mangaId = mangaId;
    }

    /**
     * Getter for <code>public.in_current_reading.user_id</code>.
     */
    @jakarta.validation.constraints.NotNull
    @NotNull
    public Long getUserId() {
        return this.userId;
    }

    /**
     * Setter for <code>public.in_current_reading.user_id</code>.
     */
    public void setUserId(@NotNull Long userId) {
        this.userId = userId;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final InCurrentReading other = (InCurrentReading) obj;
        if (this.mangaId == null) {
            if (other.mangaId != null)
                return false;
        }
        else if (!this.mangaId.equals(other.mangaId))
            return false;
        if (this.userId == null) {
            if (other.userId != null)
                return false;
        }
        else if (!this.userId.equals(other.userId))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.mangaId == null) ? 0 : this.mangaId.hashCode());
        result = prime * result + ((this.userId == null) ? 0 : this.userId.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("InCurrentReading (");

        sb.append(mangaId);
        sb.append(", ").append(userId);

        sb.append(")");
        return sb.toString();
    }
}
