/*
 * This file is generated by jOOQ.
 */
package Repositories.jooqGenEntities.tables.pojos;


import jakarta.validation.constraints.Size;

import java.beans.ConstructorProperties;
import java.io.Serializable;

import javax.annotation.processing.Generated;

import org.jetbrains.annotations.Nullable;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.18.13"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Mangareader implements Serializable {

    private static final long serialVersionUID = 1L;

    private Long userId;
    private String password;
    private String email;

    public Mangareader() {}

    public Mangareader(Mangareader value) {
        this.userId = value.userId;
        this.password = value.password;
        this.email = value.email;
    }

    @ConstructorProperties({ "userId", "password", "email" })
    public Mangareader(
        @Nullable Long userId,
        @Nullable String password,
        @Nullable String email
    ) {
        this.userId = userId;
        this.password = password;
        this.email = email;
    }

    /**
     * Getter for <code>public.mangareader.user_id</code>.
     */
    @Nullable
    public Long getUserId() {
        return this.userId;
    }

    /**
     * Setter for <code>public.mangareader.user_id</code>.
     */
    public void setUserId(@Nullable Long userId) {
        this.userId = userId;
    }

    /**
     * Getter for <code>public.mangareader.password</code>.
     */
    @Size(max = 255)
    @Nullable
    public String getPassword() {
        return this.password;
    }

    /**
     * Setter for <code>public.mangareader.password</code>.
     */
    public void setPassword(@Nullable String password) {
        this.password = password;
    }

    /**
     * Getter for <code>public.mangareader.email</code>.
     */
    @Size(max = 255)
    @Nullable
    public String getEmail() {
        return this.email;
    }

    /**
     * Setter for <code>public.mangareader.email</code>.
     */
    public void setEmail(@Nullable String email) {
        this.email = email;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final Mangareader other = (Mangareader) obj;
        if (this.userId == null) {
            if (other.userId != null)
                return false;
        }
        else if (!this.userId.equals(other.userId))
            return false;
        if (this.password == null) {
            if (other.password != null)
                return false;
        }
        else if (!this.password.equals(other.password))
            return false;
        if (this.email == null) {
            if (other.email != null)
                return false;
        }
        else if (!this.email.equals(other.email))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.userId == null) ? 0 : this.userId.hashCode());
        result = prime * result + ((this.password == null) ? 0 : this.password.hashCode());
        result = prime * result + ((this.email == null) ? 0 : this.email.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Mangareader (");

        sb.append(userId);
        sb.append(", ").append(password);
        sb.append(", ").append(email);

        sb.append(")");
        return sb.toString();
    }
}
