/*
 * This file is generated by jOOQ.
 */
package Repositories.jooqGenEntities.tables.pojos;


import jakarta.validation.constraints.Size;

import java.beans.ConstructorProperties;
import java.io.Serializable;

import javax.annotation.processing.Generated;

import org.jetbrains.annotations.NotNull;
import org.jetbrains.annotations.Nullable;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.18.13"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Page implements Serializable {

    private static final long serialVersionUID = 1L;

    private Long chapterId;
    private Long pagePlace;
    private String initPictureLink;

    public Page() {}

    public Page(Page value) {
        this.chapterId = value.chapterId;
        this.pagePlace = value.pagePlace;
        this.initPictureLink = value.initPictureLink;
    }

    @ConstructorProperties({ "chapterId", "pagePlace", "initPictureLink" })
    public Page(
        @NotNull Long chapterId,
        @NotNull Long pagePlace,
        @Nullable String initPictureLink
    ) {
        this.chapterId = chapterId;
        this.pagePlace = pagePlace;
        this.initPictureLink = initPictureLink;
    }

    /**
     * Getter for <code>public.page.chapter_id</code>.
     */
    @jakarta.validation.constraints.NotNull
    @NotNull
    public Long getChapterId() {
        return this.chapterId;
    }

    /**
     * Setter for <code>public.page.chapter_id</code>.
     */
    public void setChapterId(@NotNull Long chapterId) {
        this.chapterId = chapterId;
    }

    /**
     * Getter for <code>public.page.page_place</code>.
     */
    @jakarta.validation.constraints.NotNull
    @NotNull
    public Long getPagePlace() {
        return this.pagePlace;
    }

    /**
     * Setter for <code>public.page.page_place</code>.
     */
    public void setPagePlace(@NotNull Long pagePlace) {
        this.pagePlace = pagePlace;
    }

    /**
     * Getter for <code>public.page.init_picture_link</code>.
     */
    @Size(max = 255)
    @Nullable
    public String getInitPictureLink() {
        return this.initPictureLink;
    }

    /**
     * Setter for <code>public.page.init_picture_link</code>.
     */
    public void setInitPictureLink(@Nullable String initPictureLink) {
        this.initPictureLink = initPictureLink;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final Page other = (Page) obj;
        if (this.chapterId == null) {
            if (other.chapterId != null)
                return false;
        }
        else if (!this.chapterId.equals(other.chapterId))
            return false;
        if (this.pagePlace == null) {
            if (other.pagePlace != null)
                return false;
        }
        else if (!this.pagePlace.equals(other.pagePlace))
            return false;
        if (this.initPictureLink == null) {
            if (other.initPictureLink != null)
                return false;
        }
        else if (!this.initPictureLink.equals(other.initPictureLink))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.chapterId == null) ? 0 : this.chapterId.hashCode());
        result = prime * result + ((this.pagePlace == null) ? 0 : this.pagePlace.hashCode());
        result = prime * result + ((this.initPictureLink == null) ? 0 : this.initPictureLink.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Page (");

        sb.append(chapterId);
        sb.append(", ").append(pagePlace);
        sb.append(", ").append(initPictureLink);

        sb.append(")");
        return sb.toString();
    }
}
