/*
 * This file is generated by jOOQ.
 */
package Repositories.jooqGenEntities.tables.pojos;


import java.beans.ConstructorProperties;
import java.io.Serializable;

import javax.annotation.processing.Generated;

import org.jetbrains.annotations.Nullable;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.18.13"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Recommendation implements Serializable {

    private static final long serialVersionUID = 1L;

    private Long recommendateId;
    private Long mangaId;
    private Long userId;

    public Recommendation() {}

    public Recommendation(Recommendation value) {
        this.recommendateId = value.recommendateId;
        this.mangaId = value.mangaId;
        this.userId = value.userId;
    }

    @ConstructorProperties({ "recommendateId", "mangaId", "userId" })
    public Recommendation(
        @Nullable Long recommendateId,
        @Nullable Long mangaId,
        @Nullable Long userId
    ) {
        this.recommendateId = recommendateId;
        this.mangaId = mangaId;
        this.userId = userId;
    }

    /**
     * Getter for <code>public.recommendation.recommendate_id</code>.
     */
    @Nullable
    public Long getRecommendateId() {
        return this.recommendateId;
    }

    /**
     * Setter for <code>public.recommendation.recommendate_id</code>.
     */
    public void setRecommendateId(@Nullable Long recommendateId) {
        this.recommendateId = recommendateId;
    }

    /**
     * Getter for <code>public.recommendation.manga_id</code>.
     */
    @Nullable
    public Long getMangaId() {
        return this.mangaId;
    }

    /**
     * Setter for <code>public.recommendation.manga_id</code>.
     */
    public void setMangaId(@Nullable Long mangaId) {
        this.mangaId = mangaId;
    }

    /**
     * Getter for <code>public.recommendation.user_id</code>.
     */
    @Nullable
    public Long getUserId() {
        return this.userId;
    }

    /**
     * Setter for <code>public.recommendation.user_id</code>.
     */
    public void setUserId(@Nullable Long userId) {
        this.userId = userId;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final Recommendation other = (Recommendation) obj;
        if (this.recommendateId == null) {
            if (other.recommendateId != null)
                return false;
        }
        else if (!this.recommendateId.equals(other.recommendateId))
            return false;
        if (this.mangaId == null) {
            if (other.mangaId != null)
                return false;
        }
        else if (!this.mangaId.equals(other.mangaId))
            return false;
        if (this.userId == null) {
            if (other.userId != null)
                return false;
        }
        else if (!this.userId.equals(other.userId))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.recommendateId == null) ? 0 : this.recommendateId.hashCode());
        result = prime * result + ((this.mangaId == null) ? 0 : this.mangaId.hashCode());
        result = prime * result + ((this.userId == null) ? 0 : this.userId.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Recommendation (");

        sb.append(recommendateId);
        sb.append(", ").append(mangaId);
        sb.append(", ").append(userId);

        sb.append(")");
        return sb.toString();
    }
}
