/*
 * This file is generated by jOOQ.
 */
package Repositories.jooqGenEntities.tables.pojos;


import java.beans.ConstructorProperties;
import java.io.Serializable;

import javax.annotation.processing.Generated;

import org.jetbrains.annotations.NotNull;
import org.jetbrains.annotations.Nullable;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.18.13"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Reviews implements Serializable {

    private static final long serialVersionUID = 1L;

    private Long mangaId;
    private Long userId;
    private Integer reviewRate;

    public Reviews() {}

    public Reviews(Reviews value) {
        this.mangaId = value.mangaId;
        this.userId = value.userId;
        this.reviewRate = value.reviewRate;
    }

    @ConstructorProperties({ "mangaId", "userId", "reviewRate" })
    public Reviews(
        @NotNull Long mangaId,
        @NotNull Long userId,
        @Nullable Integer reviewRate
    ) {
        this.mangaId = mangaId;
        this.userId = userId;
        this.reviewRate = reviewRate;
    }

    /**
     * Getter for <code>public.reviews.manga_id</code>.
     */
    @jakarta.validation.constraints.NotNull
    @NotNull
    public Long getMangaId() {
        return this.mangaId;
    }

    /**
     * Setter for <code>public.reviews.manga_id</code>.
     */
    public void setMangaId(@NotNull Long mangaId) {
        this.mangaId = mangaId;
    }

    /**
     * Getter for <code>public.reviews.user_id</code>.
     */
    @jakarta.validation.constraints.NotNull
    @NotNull
    public Long getUserId() {
        return this.userId;
    }

    /**
     * Setter for <code>public.reviews.user_id</code>.
     */
    public void setUserId(@NotNull Long userId) {
        this.userId = userId;
    }

    /**
     * Getter for <code>public.reviews.review_rate</code>.
     */
    @Nullable
    public Integer getReviewRate() {
        return this.reviewRate;
    }

    /**
     * Setter for <code>public.reviews.review_rate</code>.
     */
    public void setReviewRate(@Nullable Integer reviewRate) {
        this.reviewRate = reviewRate;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final Reviews other = (Reviews) obj;
        if (this.mangaId == null) {
            if (other.mangaId != null)
                return false;
        }
        else if (!this.mangaId.equals(other.mangaId))
            return false;
        if (this.userId == null) {
            if (other.userId != null)
                return false;
        }
        else if (!this.userId.equals(other.userId))
            return false;
        if (this.reviewRate == null) {
            if (other.reviewRate != null)
                return false;
        }
        else if (!this.reviewRate.equals(other.reviewRate))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.mangaId == null) ? 0 : this.mangaId.hashCode());
        result = prime * result + ((this.userId == null) ? 0 : this.userId.hashCode());
        result = prime * result + ((this.reviewRate == null) ? 0 : this.reviewRate.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Reviews (");

        sb.append(mangaId);
        sb.append(", ").append(userId);
        sb.append(", ").append(reviewRate);

        sb.append(")");
        return sb.toString();
    }
}
