/*
 * This file is generated by jOOQ.
 */
package Repositories.jooqGenEntities.tables.pojos;


import java.beans.ConstructorProperties;
import java.io.Serializable;

import javax.annotation.processing.Generated;

import org.jetbrains.annotations.Nullable;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.18.13"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Translator implements Serializable {

    private static final long serialVersionUID = 1L;

    private Long translatorId;
    private String translatorName;

    public Translator() {}

    public Translator(Translator value) {
        this.translatorId = value.translatorId;
        this.translatorName = value.translatorName;
    }

    @ConstructorProperties({ "translatorId", "translatorName" })
    public Translator(
        @Nullable Long translatorId,
        @Nullable String translatorName
    ) {
        this.translatorId = translatorId;
        this.translatorName = translatorName;
    }

    /**
     * Getter for <code>public.translator.translator_id</code>.
     */
    @Nullable
    public Long getTranslatorId() {
        return this.translatorId;
    }

    /**
     * Setter for <code>public.translator.translator_id</code>.
     */
    public void setTranslatorId(@Nullable Long translatorId) {
        this.translatorId = translatorId;
    }

    /**
     * Getter for <code>public.translator.translator_name</code>.
     */
    @Nullable
    public String getTranslatorName() {
        return this.translatorName;
    }

    /**
     * Setter for <code>public.translator.translator_name</code>.
     */
    public void setTranslatorName(@Nullable String translatorName) {
        this.translatorName = translatorName;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final Translator other = (Translator) obj;
        if (this.translatorId == null) {
            if (other.translatorId != null)
                return false;
        }
        else if (!this.translatorId.equals(other.translatorId))
            return false;
        if (this.translatorName == null) {
            if (other.translatorName != null)
                return false;
        }
        else if (!this.translatorName.equals(other.translatorName))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.translatorId == null) ? 0 : this.translatorId.hashCode());
        result = prime * result + ((this.translatorName == null) ? 0 : this.translatorName.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Translator (");

        sb.append(translatorId);
        sb.append(", ").append(translatorName);

        sb.append(")");
        return sb.toString();
    }
}
