/*
 * This file is generated by jOOQ.
 */
package Repositories.jooqGenEntities;


import Repositories.jooqGenEntities.tables.Author;
import Repositories.jooqGenEntities.tables.Ban;
import Repositories.jooqGenEntities.tables.Chapter;
import Repositories.jooqGenEntities.tables.Commentary;
import Repositories.jooqGenEntities.tables.InCurrentReading;
import Repositories.jooqGenEntities.tables.Manga;
import Repositories.jooqGenEntities.tables.MangaTypeTag;
import Repositories.jooqGenEntities.tables.Mangareader;
import Repositories.jooqGenEntities.tables.Page;
import Repositories.jooqGenEntities.tables.Recommendation;
import Repositories.jooqGenEntities.tables.Reviews;
import Repositories.jooqGenEntities.tables.ToRead;
import Repositories.jooqGenEntities.tables.Translator;

import javax.annotation.processing.Generated;


/**
 * Convenience access to all tables in public.
 */
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.18.13"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>public.author</code>.
     */
    public static final Author AUTHOR = Author.AUTHOR;

    /**
     * The table <code>public.ban</code>.
     */
    public static final Ban BAN = Ban.BAN;

    /**
     * The table <code>public.chapter</code>.
     */
    public static final Chapter CHAPTER = Chapter.CHAPTER;

    /**
     * The table <code>public.commentary</code>.
     */
    public static final Commentary COMMENTARY = Commentary.COMMENTARY;

    /**
     * The table <code>public.in_current_reading</code>.
     */
    public static final InCurrentReading IN_CURRENT_READING = InCurrentReading.IN_CURRENT_READING;

    /**
     * The table <code>public.manga</code>.
     */
    public static final Manga MANGA = Manga.MANGA;

    /**
     * The table <code>public.manga_type_tag</code>.
     */
    public static final MangaTypeTag MANGA_TYPE_TAG = MangaTypeTag.MANGA_TYPE_TAG;

    /**
     * The table <code>public.mangareader</code>.
     */
    public static final Mangareader MANGAREADER = Mangareader.MANGAREADER;

    /**
     * The table <code>public.page</code>.
     */
    public static final Page PAGE = Page.PAGE;

    /**
     * The table <code>public.recommendation</code>.
     */
    public static final Recommendation RECOMMENDATION = Recommendation.RECOMMENDATION;

    /**
     * The table <code>public.reviews</code>.
     */
    public static final Reviews REVIEWS = Reviews.REVIEWS;

    /**
     * The table <code>public.to_read</code>.
     */
    public static final ToRead TO_READ = ToRead.TO_READ;

    /**
     * The table <code>public.translator</code>.
     */
    public static final Translator TRANSLATOR = Translator.TRANSLATOR;
}
