/*
 * This file is generated by jOOQ.
 */
package Repositories.jooqGenEntities.tables;


import Repositories.jooqGenEntities.Keys;
import Repositories.jooqGenEntities.Public;
import Repositories.jooqGenEntities.tables.records.BanRecord;

import java.util.Arrays;
import java.util.List;
import java.util.function.Function;

import javax.annotation.processing.Generated;

import org.jetbrains.annotations.NotNull;
import org.jetbrains.annotations.Nullable;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Function3;
import org.jooq.Identity;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Records;
import org.jooq.Row3;
import org.jooq.Schema;
import org.jooq.SelectField;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.18.13"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Ban extends TableImpl<BanRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.ban</code>
     */
    public static final Ban BAN = new Ban();

    /**
     * The class holding records for this type
     */
    @Override
    @NotNull
    public Class<BanRecord> getRecordType() {
        return BanRecord.class;
    }

    /**
     * The column <code>public.ban.ban_id</code>.
     */
    public final TableField<BanRecord, Long> BAN_ID = createField(DSL.name("ban_id"), SQLDataType.BIGINT.nullable(false).identity(true), this, "");

    /**
     * The column <code>public.ban.ban_enum</code>.
     */
    public final TableField<BanRecord, String> BAN_ENUM = createField(DSL.name("ban_enum"), SQLDataType.VARCHAR(255), this, "");

    /**
     * The column <code>public.ban.user_id</code>.
     */
    public final TableField<BanRecord, Long> USER_ID = createField(DSL.name("user_id"), SQLDataType.BIGINT, this, "");

    private Ban(Name alias, Table<BanRecord> aliased) {
        this(alias, aliased, null);
    }

    private Ban(Name alias, Table<BanRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table());
    }

    /**
     * Create an aliased <code>public.ban</code> table reference
     */
    public Ban(String alias) {
        this(DSL.name(alias), BAN);
    }

    /**
     * Create an aliased <code>public.ban</code> table reference
     */
    public Ban(Name alias) {
        this(alias, BAN);
    }

    /**
     * Create a <code>public.ban</code> table reference
     */
    public Ban() {
        this(DSL.name("ban"), null);
    }

    public <O extends Record> Ban(Table<O> child, ForeignKey<O, BanRecord> key) {
        super(child, key, BAN);
    }

    @Override
    @Nullable
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    @NotNull
    public Identity<BanRecord, Long> getIdentity() {
        return (Identity<BanRecord, Long>) super.getIdentity();
    }

    @Override
    @NotNull
    public UniqueKey<BanRecord> getPrimaryKey() {
        return Keys.BAN_PKEY;
    }

    @Override
    @NotNull
    public List<ForeignKey<BanRecord, ?>> getReferences() {
        return Arrays.asList(Keys.BAN__BAN_USER_ID_FKEY);
    }

    private transient Mangareader _mangareader;

    /**
     * Get the implicit join path to the <code>public.mangareader</code> table.
     */
    public Mangareader mangareader() {
        if (_mangareader == null)
            _mangareader = new Mangareader(this, Keys.BAN__BAN_USER_ID_FKEY);

        return _mangareader;
    }

    @Override
    @NotNull
    public Ban as(String alias) {
        return new Ban(DSL.name(alias), this);
    }

    @Override
    @NotNull
    public Ban as(Name alias) {
        return new Ban(alias, this);
    }

    @Override
    @NotNull
    public Ban as(Table<?> alias) {
        return new Ban(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    @NotNull
    public Ban rename(String name) {
        return new Ban(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    @NotNull
    public Ban rename(Name name) {
        return new Ban(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    @NotNull
    public Ban rename(Table<?> name) {
        return new Ban(name.getQualifiedName(), null);
    }

    // -------------------------------------------------------------------------
    // Row3 type methods
    // -------------------------------------------------------------------------

    @Override
    @NotNull
    public Row3<Long, String, Long> fieldsRow() {
        return (Row3) super.fieldsRow();
    }

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Function)}.
     */
    public <U> SelectField<U> mapping(Function3<? super Long, ? super String, ? super Long, ? extends U> from) {
        return convertFrom(Records.mapping(from));
    }

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Class,
     * Function)}.
     */
    public <U> SelectField<U> mapping(Class<U> toType, Function3<? super Long, ? super String, ? super Long, ? extends U> from) {
        return convertFrom(toType, Records.mapping(from));
    }
}
