/*
 * This file is generated by jOOQ.
 */
package Repositories.jooqGenEntities.tables;


import Repositories.jooqGenEntities.Keys;
import Repositories.jooqGenEntities.Public;
import Repositories.jooqGenEntities.tables.records.ChapterRecord;

import java.util.Arrays;
import java.util.List;
import java.util.function.Function;

import javax.annotation.processing.Generated;

import org.jetbrains.annotations.NotNull;
import org.jetbrains.annotations.Nullable;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Function3;
import org.jooq.Identity;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Records;
import org.jooq.Row3;
import org.jooq.Schema;
import org.jooq.SelectField;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.18.13"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Chapter extends TableImpl<ChapterRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.chapter</code>
     */
    public static final Chapter CHAPTER = new Chapter();

    /**
     * The class holding records for this type
     */
    @Override
    @NotNull
    public Class<ChapterRecord> getRecordType() {
        return ChapterRecord.class;
    }

    /**
     * The column <code>public.chapter.chapter_id</code>.
     */
    public final TableField<ChapterRecord, Long> CHAPTER_ID = createField(DSL.name("chapter_id"), SQLDataType.BIGINT.nullable(false).identity(true), this, "");

    /**
     * The column <code>public.chapter.init_picture_link</code>.
     */
    public final TableField<ChapterRecord, String> INIT_PICTURE_LINK = createField(DSL.name("init_picture_link"), SQLDataType.VARCHAR(255), this, "");

    /**
     * The column <code>public.chapter.manga_id</code>.
     */
    public final TableField<ChapterRecord, Long> MANGA_ID = createField(DSL.name("manga_id"), SQLDataType.BIGINT, this, "");

    private Chapter(Name alias, Table<ChapterRecord> aliased) {
        this(alias, aliased, null);
    }

    private Chapter(Name alias, Table<ChapterRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table());
    }

    /**
     * Create an aliased <code>public.chapter</code> table reference
     */
    public Chapter(String alias) {
        this(DSL.name(alias), CHAPTER);
    }

    /**
     * Create an aliased <code>public.chapter</code> table reference
     */
    public Chapter(Name alias) {
        this(alias, CHAPTER);
    }

    /**
     * Create a <code>public.chapter</code> table reference
     */
    public Chapter() {
        this(DSL.name("chapter"), null);
    }

    public <O extends Record> Chapter(Table<O> child, ForeignKey<O, ChapterRecord> key) {
        super(child, key, CHAPTER);
    }

    @Override
    @Nullable
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    @NotNull
    public Identity<ChapterRecord, Long> getIdentity() {
        return (Identity<ChapterRecord, Long>) super.getIdentity();
    }

    @Override
    @NotNull
    public UniqueKey<ChapterRecord> getPrimaryKey() {
        return Keys.CHAPTER_PKEY;
    }

    @Override
    @NotNull
    public List<ForeignKey<ChapterRecord, ?>> getReferences() {
        return Arrays.asList(Keys.CHAPTER__CHAPTER_MANGA_ID_FKEY);
    }

    private transient Manga _manga;

    /**
     * Get the implicit join path to the <code>public.manga</code> table.
     */
    public Manga manga() {
        if (_manga == null)
            _manga = new Manga(this, Keys.CHAPTER__CHAPTER_MANGA_ID_FKEY);

        return _manga;
    }

    @Override
    @NotNull
    public Chapter as(String alias) {
        return new Chapter(DSL.name(alias), this);
    }

    @Override
    @NotNull
    public Chapter as(Name alias) {
        return new Chapter(alias, this);
    }

    @Override
    @NotNull
    public Chapter as(Table<?> alias) {
        return new Chapter(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    @NotNull
    public Chapter rename(String name) {
        return new Chapter(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    @NotNull
    public Chapter rename(Name name) {
        return new Chapter(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    @NotNull
    public Chapter rename(Table<?> name) {
        return new Chapter(name.getQualifiedName(), null);
    }

    // -------------------------------------------------------------------------
    // Row3 type methods
    // -------------------------------------------------------------------------

    @Override
    @NotNull
    public Row3<Long, String, Long> fieldsRow() {
        return (Row3) super.fieldsRow();
    }

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Function)}.
     */
    public <U> SelectField<U> mapping(Function3<? super Long, ? super String, ? super Long, ? extends U> from) {
        return convertFrom(Records.mapping(from));
    }

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Class,
     * Function)}.
     */
    public <U> SelectField<U> mapping(Class<U> toType, Function3<? super Long, ? super String, ? super Long, ? extends U> from) {
        return convertFrom(toType, Records.mapping(from));
    }
}
