/*
 * This file is generated by jOOQ.
 */
package Repositories.jooqGenEntities.tables;


import Repositories.jooqGenEntities.Keys;
import Repositories.jooqGenEntities.Public;
import Repositories.jooqGenEntities.tables.records.CommentaryRecord;

import java.util.Arrays;
import java.util.List;
import java.util.function.Function;

import javax.annotation.processing.Generated;

import org.jetbrains.annotations.NotNull;
import org.jetbrains.annotations.Nullable;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Function4;
import org.jooq.Identity;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Records;
import org.jooq.Row4;
import org.jooq.Schema;
import org.jooq.SelectField;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.18.13"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Commentary extends TableImpl<CommentaryRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.commentary</code>
     */
    public static final Commentary COMMENTARY = new Commentary();

    /**
     * The class holding records for this type
     */
    @Override
    @NotNull
    public Class<CommentaryRecord> getRecordType() {
        return CommentaryRecord.class;
    }

    /**
     * The column <code>public.commentary.commentary_id</code>.
     */
    public final TableField<CommentaryRecord, Long> COMMENTARY_ID = createField(DSL.name("commentary_id"), SQLDataType.BIGINT.nullable(false).identity(true), this, "");

    /**
     * The column <code>public.commentary.commentary</code>.
     */
    public final TableField<CommentaryRecord, String> COMMENTARY_ = createField(DSL.name("commentary"), SQLDataType.VARCHAR(255), this, "");

    /**
     * The column <code>public.commentary.manga_id</code>.
     */
    public final TableField<CommentaryRecord, Long> MANGA_ID = createField(DSL.name("manga_id"), SQLDataType.BIGINT, this, "");

    /**
     * The column <code>public.commentary.user_id</code>.
     */
    public final TableField<CommentaryRecord, Long> USER_ID = createField(DSL.name("user_id"), SQLDataType.BIGINT, this, "");

    private Commentary(Name alias, Table<CommentaryRecord> aliased) {
        this(alias, aliased, null);
    }

    private Commentary(Name alias, Table<CommentaryRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table());
    }

    /**
     * Create an aliased <code>public.commentary</code> table reference
     */
    public Commentary(String alias) {
        this(DSL.name(alias), COMMENTARY);
    }

    /**
     * Create an aliased <code>public.commentary</code> table reference
     */
    public Commentary(Name alias) {
        this(alias, COMMENTARY);
    }

    /**
     * Create a <code>public.commentary</code> table reference
     */
    public Commentary() {
        this(DSL.name("commentary"), null);
    }

    public <O extends Record> Commentary(Table<O> child, ForeignKey<O, CommentaryRecord> key) {
        super(child, key, COMMENTARY);
    }

    @Override
    @Nullable
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    @NotNull
    public Identity<CommentaryRecord, Long> getIdentity() {
        return (Identity<CommentaryRecord, Long>) super.getIdentity();
    }

    @Override
    @NotNull
    public UniqueKey<CommentaryRecord> getPrimaryKey() {
        return Keys.COMMENTARY_PKEY;
    }

    @Override
    @NotNull
    public List<ForeignKey<CommentaryRecord, ?>> getReferences() {
        return Arrays.asList(Keys.COMMENTARY__COMMENTARY_MANGA_ID_FKEY, Keys.COMMENTARY__COMMENTARY_USER_ID_FKEY);
    }

    private transient Manga _manga;
    private transient Mangareader _mangareader;

    /**
     * Get the implicit join path to the <code>public.manga</code> table.
     */
    public Manga manga() {
        if (_manga == null)
            _manga = new Manga(this, Keys.COMMENTARY__COMMENTARY_MANGA_ID_FKEY);

        return _manga;
    }

    /**
     * Get the implicit join path to the <code>public.mangareader</code> table.
     */
    public Mangareader mangareader() {
        if (_mangareader == null)
            _mangareader = new Mangareader(this, Keys.COMMENTARY__COMMENTARY_USER_ID_FKEY);

        return _mangareader;
    }

    @Override
    @NotNull
    public Commentary as(String alias) {
        return new Commentary(DSL.name(alias), this);
    }

    @Override
    @NotNull
    public Commentary as(Name alias) {
        return new Commentary(alias, this);
    }

    @Override
    @NotNull
    public Commentary as(Table<?> alias) {
        return new Commentary(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    @NotNull
    public Commentary rename(String name) {
        return new Commentary(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    @NotNull
    public Commentary rename(Name name) {
        return new Commentary(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    @NotNull
    public Commentary rename(Table<?> name) {
        return new Commentary(name.getQualifiedName(), null);
    }

    // -------------------------------------------------------------------------
    // Row4 type methods
    // -------------------------------------------------------------------------

    @Override
    @NotNull
    public Row4<Long, String, Long, Long> fieldsRow() {
        return (Row4) super.fieldsRow();
    }

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Function)}.
     */
    public <U> SelectField<U> mapping(Function4<? super Long, ? super String, ? super Long, ? super Long, ? extends U> from) {
        return convertFrom(Records.mapping(from));
    }

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Class,
     * Function)}.
     */
    public <U> SelectField<U> mapping(Class<U> toType, Function4<? super Long, ? super String, ? super Long, ? super Long, ? extends U> from) {
        return convertFrom(toType, Records.mapping(from));
    }
}
