/*
 * This file is generated by jOOQ.
 */
package Repositories.jooqGenEntities.tables;


import Repositories.jooqGenEntities.Keys;
import Repositories.jooqGenEntities.Public;
import Repositories.jooqGenEntities.tables.records.InCurrentReadingRecord;

import java.util.Arrays;
import java.util.List;
import java.util.function.Function;

import javax.annotation.processing.Generated;

import org.jetbrains.annotations.NotNull;
import org.jetbrains.annotations.Nullable;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Function2;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Records;
import org.jooq.Row2;
import org.jooq.Schema;
import org.jooq.SelectField;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.18.13"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class InCurrentReading extends TableImpl<InCurrentReadingRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.in_current_reading</code>
     */
    public static final InCurrentReading IN_CURRENT_READING = new InCurrentReading();

    /**
     * The class holding records for this type
     */
    @Override
    @NotNull
    public Class<InCurrentReadingRecord> getRecordType() {
        return InCurrentReadingRecord.class;
    }

    /**
     * The column <code>public.in_current_reading.manga_id</code>.
     */
    public final TableField<InCurrentReadingRecord, Long> MANGA_ID = createField(DSL.name("manga_id"), SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>public.in_current_reading.user_id</code>.
     */
    public final TableField<InCurrentReadingRecord, Long> USER_ID = createField(DSL.name("user_id"), SQLDataType.BIGINT.nullable(false), this, "");

    private InCurrentReading(Name alias, Table<InCurrentReadingRecord> aliased) {
        this(alias, aliased, null);
    }

    private InCurrentReading(Name alias, Table<InCurrentReadingRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table());
    }

    /**
     * Create an aliased <code>public.in_current_reading</code> table reference
     */
    public InCurrentReading(String alias) {
        this(DSL.name(alias), IN_CURRENT_READING);
    }

    /**
     * Create an aliased <code>public.in_current_reading</code> table reference
     */
    public InCurrentReading(Name alias) {
        this(alias, IN_CURRENT_READING);
    }

    /**
     * Create a <code>public.in_current_reading</code> table reference
     */
    public InCurrentReading() {
        this(DSL.name("in_current_reading"), null);
    }

    public <O extends Record> InCurrentReading(Table<O> child, ForeignKey<O, InCurrentReadingRecord> key) {
        super(child, key, IN_CURRENT_READING);
    }

    @Override
    @Nullable
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    @NotNull
    public UniqueKey<InCurrentReadingRecord> getPrimaryKey() {
        return Keys.IN_CURRENT_READING_PKEY;
    }

    @Override
    @NotNull
    public List<ForeignKey<InCurrentReadingRecord, ?>> getReferences() {
        return Arrays.asList(Keys.IN_CURRENT_READING__IN_CURRENT_READING_MANGA_ID_FKEY, Keys.IN_CURRENT_READING__IN_CURRENT_READING_USER_ID_FKEY);
    }

    private transient Manga _manga;
    private transient Mangareader _mangareader;

    /**
     * Get the implicit join path to the <code>public.manga</code> table.
     */
    public Manga manga() {
        if (_manga == null)
            _manga = new Manga(this, Keys.IN_CURRENT_READING__IN_CURRENT_READING_MANGA_ID_FKEY);

        return _manga;
    }

    /**
     * Get the implicit join path to the <code>public.mangareader</code> table.
     */
    public Mangareader mangareader() {
        if (_mangareader == null)
            _mangareader = new Mangareader(this, Keys.IN_CURRENT_READING__IN_CURRENT_READING_USER_ID_FKEY);

        return _mangareader;
    }

    @Override
    @NotNull
    public InCurrentReading as(String alias) {
        return new InCurrentReading(DSL.name(alias), this);
    }

    @Override
    @NotNull
    public InCurrentReading as(Name alias) {
        return new InCurrentReading(alias, this);
    }

    @Override
    @NotNull
    public InCurrentReading as(Table<?> alias) {
        return new InCurrentReading(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    @NotNull
    public InCurrentReading rename(String name) {
        return new InCurrentReading(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    @NotNull
    public InCurrentReading rename(Name name) {
        return new InCurrentReading(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    @NotNull
    public InCurrentReading rename(Table<?> name) {
        return new InCurrentReading(name.getQualifiedName(), null);
    }

    // -------------------------------------------------------------------------
    // Row2 type methods
    // -------------------------------------------------------------------------

    @Override
    @NotNull
    public Row2<Long, Long> fieldsRow() {
        return (Row2) super.fieldsRow();
    }

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Function)}.
     */
    public <U> SelectField<U> mapping(Function2<? super Long, ? super Long, ? extends U> from) {
        return convertFrom(Records.mapping(from));
    }

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Class,
     * Function)}.
     */
    public <U> SelectField<U> mapping(Class<U> toType, Function2<? super Long, ? super Long, ? extends U> from) {
        return convertFrom(toType, Records.mapping(from));
    }
}
