/*
 * This file is generated by jOOQ.
 */
package Repositories.jooqGenEntities.tables;


import Repositories.jooqGenEntities.Keys;
import Repositories.jooqGenEntities.Public;
import Repositories.jooqGenEntities.tables.records.MangaTypeTagRecord;

import java.util.Arrays;
import java.util.List;
import java.util.function.Function;

import javax.annotation.processing.Generated;

import org.jetbrains.annotations.NotNull;
import org.jetbrains.annotations.Nullable;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Function3;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Records;
import org.jooq.Row3;
import org.jooq.Schema;
import org.jooq.SelectField;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.18.13"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class MangaTypeTag extends TableImpl<MangaTypeTagRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.manga_type_tag</code>
     */
    public static final MangaTypeTag MANGA_TYPE_TAG = new MangaTypeTag();

    /**
     * The class holding records for this type
     */
    @Override
    @NotNull
    public Class<MangaTypeTagRecord> getRecordType() {
        return MangaTypeTagRecord.class;
    }

    /**
     * The column <code>public.manga_type_tag.tag</code>.
     */
    public final TableField<MangaTypeTagRecord, String> TAG = createField(DSL.name("tag"), SQLDataType.CLOB, this, "");

    /**
     * The column <code>public.manga_type_tag._type</code>.
     */
    public final TableField<MangaTypeTagRecord, String> _TYPE = createField(DSL.name("_type"), SQLDataType.CLOB, this, "");

    /**
     * The column <code>public.manga_type_tag.manga_id</code>.
     */
    public final TableField<MangaTypeTagRecord, Long> MANGA_ID = createField(DSL.name("manga_id"), SQLDataType.BIGINT.nullable(false), this, "");

    private MangaTypeTag(Name alias, Table<MangaTypeTagRecord> aliased) {
        this(alias, aliased, null);
    }

    private MangaTypeTag(Name alias, Table<MangaTypeTagRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table());
    }

    /**
     * Create an aliased <code>public.manga_type_tag</code> table reference
     */
    public MangaTypeTag(String alias) {
        this(DSL.name(alias), MANGA_TYPE_TAG);
    }

    /**
     * Create an aliased <code>public.manga_type_tag</code> table reference
     */
    public MangaTypeTag(Name alias) {
        this(alias, MANGA_TYPE_TAG);
    }

    /**
     * Create a <code>public.manga_type_tag</code> table reference
     */
    public MangaTypeTag() {
        this(DSL.name("manga_type_tag"), null);
    }

    public <O extends Record> MangaTypeTag(Table<O> child, ForeignKey<O, MangaTypeTagRecord> key) {
        super(child, key, MANGA_TYPE_TAG);
    }

    @Override
    @Nullable
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    @NotNull
    public UniqueKey<MangaTypeTagRecord> getPrimaryKey() {
        return Keys.MANGA_TYPE_TAG_PKEY;
    }

    @Override
    @NotNull
    public List<ForeignKey<MangaTypeTagRecord, ?>> getReferences() {
        return Arrays.asList(Keys.MANGA_TYPE_TAG__MANGA_TYPE_TAG_MANGA_ID_FKEY);
    }

    private transient Manga _manga;

    /**
     * Get the implicit join path to the <code>public.manga</code> table.
     */
    public Manga manga() {
        if (_manga == null)
            _manga = new Manga(this, Keys.MANGA_TYPE_TAG__MANGA_TYPE_TAG_MANGA_ID_FKEY);

        return _manga;
    }

    @Override
    @NotNull
    public MangaTypeTag as(String alias) {
        return new MangaTypeTag(DSL.name(alias), this);
    }

    @Override
    @NotNull
    public MangaTypeTag as(Name alias) {
        return new MangaTypeTag(alias, this);
    }

    @Override
    @NotNull
    public MangaTypeTag as(Table<?> alias) {
        return new MangaTypeTag(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    @NotNull
    public MangaTypeTag rename(String name) {
        return new MangaTypeTag(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    @NotNull
    public MangaTypeTag rename(Name name) {
        return new MangaTypeTag(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    @NotNull
    public MangaTypeTag rename(Table<?> name) {
        return new MangaTypeTag(name.getQualifiedName(), null);
    }

    // -------------------------------------------------------------------------
    // Row3 type methods
    // -------------------------------------------------------------------------

    @Override
    @NotNull
    public Row3<String, String, Long> fieldsRow() {
        return (Row3) super.fieldsRow();
    }

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Function)}.
     */
    public <U> SelectField<U> mapping(Function3<? super String, ? super String, ? super Long, ? extends U> from) {
        return convertFrom(Records.mapping(from));
    }

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Class,
     * Function)}.
     */
    public <U> SelectField<U> mapping(Class<U> toType, Function3<? super String, ? super String, ? super Long, ? extends U> from) {
        return convertFrom(toType, Records.mapping(from));
    }
}
