/*
 * This file is generated by jOOQ.
 */
package Repositories.jooqGenEntities.tables;


import Repositories.jooqGenEntities.Keys;
import Repositories.jooqGenEntities.Public;
import Repositories.jooqGenEntities.tables.records.MangareaderRecord;

import java.util.function.Function;

import javax.annotation.processing.Generated;

import org.jetbrains.annotations.NotNull;
import org.jetbrains.annotations.Nullable;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Function3;
import org.jooq.Identity;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Records;
import org.jooq.Row3;
import org.jooq.Schema;
import org.jooq.SelectField;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.18.13"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Mangareader extends TableImpl<MangareaderRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.mangareader</code>
     */
    public static final Mangareader MANGAREADER = new Mangareader();

    /**
     * The class holding records for this type
     */
    @Override
    @NotNull
    public Class<MangareaderRecord> getRecordType() {
        return MangareaderRecord.class;
    }

    /**
     * The column <code>public.mangareader.user_id</code>.
     */
    public final TableField<MangareaderRecord, Long> USER_ID = createField(DSL.name("user_id"), SQLDataType.BIGINT.nullable(false).identity(true), this, "");

    /**
     * The column <code>public.mangareader.password</code>.
     */
    public final TableField<MangareaderRecord, String> PASSWORD = createField(DSL.name("password"), SQLDataType.VARCHAR(255), this, "");

    /**
     * The column <code>public.mangareader.email</code>.
     */
    public final TableField<MangareaderRecord, String> EMAIL = createField(DSL.name("email"), SQLDataType.VARCHAR(255), this, "");

    private Mangareader(Name alias, Table<MangareaderRecord> aliased) {
        this(alias, aliased, null);
    }

    private Mangareader(Name alias, Table<MangareaderRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table());
    }

    /**
     * Create an aliased <code>public.mangareader</code> table reference
     */
    public Mangareader(String alias) {
        this(DSL.name(alias), MANGAREADER);
    }

    /**
     * Create an aliased <code>public.mangareader</code> table reference
     */
    public Mangareader(Name alias) {
        this(alias, MANGAREADER);
    }

    /**
     * Create a <code>public.mangareader</code> table reference
     */
    public Mangareader() {
        this(DSL.name("mangareader"), null);
    }

    public <O extends Record> Mangareader(Table<O> child, ForeignKey<O, MangareaderRecord> key) {
        super(child, key, MANGAREADER);
    }

    @Override
    @Nullable
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    @NotNull
    public Identity<MangareaderRecord, Long> getIdentity() {
        return (Identity<MangareaderRecord, Long>) super.getIdentity();
    }

    @Override
    @NotNull
    public UniqueKey<MangareaderRecord> getPrimaryKey() {
        return Keys.MANGAREADER_PKEY;
    }

    @Override
    @NotNull
    public Mangareader as(String alias) {
        return new Mangareader(DSL.name(alias), this);
    }

    @Override
    @NotNull
    public Mangareader as(Name alias) {
        return new Mangareader(alias, this);
    }

    @Override
    @NotNull
    public Mangareader as(Table<?> alias) {
        return new Mangareader(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    @NotNull
    public Mangareader rename(String name) {
        return new Mangareader(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    @NotNull
    public Mangareader rename(Name name) {
        return new Mangareader(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    @NotNull
    public Mangareader rename(Table<?> name) {
        return new Mangareader(name.getQualifiedName(), null);
    }

    // -------------------------------------------------------------------------
    // Row3 type methods
    // -------------------------------------------------------------------------

    @Override
    @NotNull
    public Row3<Long, String, String> fieldsRow() {
        return (Row3) super.fieldsRow();
    }

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Function)}.
     */
    public <U> SelectField<U> mapping(Function3<? super Long, ? super String, ? super String, ? extends U> from) {
        return convertFrom(Records.mapping(from));
    }

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Class,
     * Function)}.
     */
    public <U> SelectField<U> mapping(Class<U> toType, Function3<? super Long, ? super String, ? super String, ? extends U> from) {
        return convertFrom(toType, Records.mapping(from));
    }
}
