/*
 * This file is generated by jOOQ.
 */
package Repositories.jooqGenEntities.tables;


import Repositories.jooqGenEntities.Keys;
import Repositories.jooqGenEntities.Public;
import Repositories.jooqGenEntities.tables.records.RecommendationRecord;

import java.util.Arrays;
import java.util.List;
import java.util.function.Function;

import javax.annotation.processing.Generated;

import org.jetbrains.annotations.NotNull;
import org.jetbrains.annotations.Nullable;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Function3;
import org.jooq.Identity;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Records;
import org.jooq.Row3;
import org.jooq.Schema;
import org.jooq.SelectField;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.18.13"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Recommendation extends TableImpl<RecommendationRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.recommendation</code>
     */
    public static final Recommendation RECOMMENDATION = new Recommendation();

    /**
     * The class holding records for this type
     */
    @Override
    @NotNull
    public Class<RecommendationRecord> getRecordType() {
        return RecommendationRecord.class;
    }

    /**
     * The column <code>public.recommendation.recommendate_id</code>.
     */
    public final TableField<RecommendationRecord, Long> RECOMMENDATE_ID = createField(DSL.name("recommendate_id"), SQLDataType.BIGINT.nullable(false).identity(true), this, "");

    /**
     * The column <code>public.recommendation.manga_id</code>.
     */
    public final TableField<RecommendationRecord, Long> MANGA_ID = createField(DSL.name("manga_id"), SQLDataType.BIGINT, this, "");

    /**
     * The column <code>public.recommendation.user_id</code>.
     */
    public final TableField<RecommendationRecord, Long> USER_ID = createField(DSL.name("user_id"), SQLDataType.BIGINT, this, "");

    private Recommendation(Name alias, Table<RecommendationRecord> aliased) {
        this(alias, aliased, null);
    }

    private Recommendation(Name alias, Table<RecommendationRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table());
    }

    /**
     * Create an aliased <code>public.recommendation</code> table reference
     */
    public Recommendation(String alias) {
        this(DSL.name(alias), RECOMMENDATION);
    }

    /**
     * Create an aliased <code>public.recommendation</code> table reference
     */
    public Recommendation(Name alias) {
        this(alias, RECOMMENDATION);
    }

    /**
     * Create a <code>public.recommendation</code> table reference
     */
    public Recommendation() {
        this(DSL.name("recommendation"), null);
    }

    public <O extends Record> Recommendation(Table<O> child, ForeignKey<O, RecommendationRecord> key) {
        super(child, key, RECOMMENDATION);
    }

    @Override
    @Nullable
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    @NotNull
    public Identity<RecommendationRecord, Long> getIdentity() {
        return (Identity<RecommendationRecord, Long>) super.getIdentity();
    }

    @Override
    @NotNull
    public UniqueKey<RecommendationRecord> getPrimaryKey() {
        return Keys.RECOMMENDATION_PKEY;
    }

    @Override
    @NotNull
    public List<ForeignKey<RecommendationRecord, ?>> getReferences() {
        return Arrays.asList(Keys.RECOMMENDATION__RECOMMENDATION_MANGA_ID_FKEY, Keys.RECOMMENDATION__RECOMMENDATION_USER_ID_FKEY);
    }

    private transient Manga _manga;
    private transient Mangareader _mangareader;

    /**
     * Get the implicit join path to the <code>public.manga</code> table.
     */
    public Manga manga() {
        if (_manga == null)
            _manga = new Manga(this, Keys.RECOMMENDATION__RECOMMENDATION_MANGA_ID_FKEY);

        return _manga;
    }

    /**
     * Get the implicit join path to the <code>public.mangareader</code> table.
     */
    public Mangareader mangareader() {
        if (_mangareader == null)
            _mangareader = new Mangareader(this, Keys.RECOMMENDATION__RECOMMENDATION_USER_ID_FKEY);

        return _mangareader;
    }

    @Override
    @NotNull
    public Recommendation as(String alias) {
        return new Recommendation(DSL.name(alias), this);
    }

    @Override
    @NotNull
    public Recommendation as(Name alias) {
        return new Recommendation(alias, this);
    }

    @Override
    @NotNull
    public Recommendation as(Table<?> alias) {
        return new Recommendation(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    @NotNull
    public Recommendation rename(String name) {
        return new Recommendation(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    @NotNull
    public Recommendation rename(Name name) {
        return new Recommendation(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    @NotNull
    public Recommendation rename(Table<?> name) {
        return new Recommendation(name.getQualifiedName(), null);
    }

    // -------------------------------------------------------------------------
    // Row3 type methods
    // -------------------------------------------------------------------------

    @Override
    @NotNull
    public Row3<Long, Long, Long> fieldsRow() {
        return (Row3) super.fieldsRow();
    }

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Function)}.
     */
    public <U> SelectField<U> mapping(Function3<? super Long, ? super Long, ? super Long, ? extends U> from) {
        return convertFrom(Records.mapping(from));
    }

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Class,
     * Function)}.
     */
    public <U> SelectField<U> mapping(Class<U> toType, Function3<? super Long, ? super Long, ? super Long, ? extends U> from) {
        return convertFrom(toType, Records.mapping(from));
    }
}
