/*
 * This file is generated by jOOQ.
 */
package Repositories.jooqGenEntities.tables;


import Repositories.jooqGenEntities.Keys;
import Repositories.jooqGenEntities.Public;
import Repositories.jooqGenEntities.tables.records.ToReadRecord;

import java.util.Arrays;
import java.util.List;
import java.util.function.Function;

import javax.annotation.processing.Generated;

import org.jetbrains.annotations.NotNull;
import org.jetbrains.annotations.Nullable;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Function2;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Records;
import org.jooq.Row2;
import org.jooq.Schema;
import org.jooq.SelectField;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.18.13"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ToRead extends TableImpl<ToReadRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.to_read</code>
     */
    public static final ToRead TO_READ = new ToRead();

    /**
     * The class holding records for this type
     */
    @Override
    @NotNull
    public Class<ToReadRecord> getRecordType() {
        return ToReadRecord.class;
    }

    /**
     * The column <code>public.to_read.manga_id</code>.
     */
    public final TableField<ToReadRecord, Long> MANGA_ID = createField(DSL.name("manga_id"), SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>public.to_read.user_id</code>.
     */
    public final TableField<ToReadRecord, Long> USER_ID = createField(DSL.name("user_id"), SQLDataType.BIGINT.nullable(false), this, "");

    private ToRead(Name alias, Table<ToReadRecord> aliased) {
        this(alias, aliased, null);
    }

    private ToRead(Name alias, Table<ToReadRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table());
    }

    /**
     * Create an aliased <code>public.to_read</code> table reference
     */
    public ToRead(String alias) {
        this(DSL.name(alias), TO_READ);
    }

    /**
     * Create an aliased <code>public.to_read</code> table reference
     */
    public ToRead(Name alias) {
        this(alias, TO_READ);
    }

    /**
     * Create a <code>public.to_read</code> table reference
     */
    public ToRead() {
        this(DSL.name("to_read"), null);
    }

    public <O extends Record> ToRead(Table<O> child, ForeignKey<O, ToReadRecord> key) {
        super(child, key, TO_READ);
    }

    @Override
    @Nullable
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    @NotNull
    public UniqueKey<ToReadRecord> getPrimaryKey() {
        return Keys.TO_READ_PKEY;
    }

    @Override
    @NotNull
    public List<ForeignKey<ToReadRecord, ?>> getReferences() {
        return Arrays.asList(Keys.TO_READ__TO_READ_MANGA_ID_FKEY, Keys.TO_READ__TO_READ_USER_ID_FKEY);
    }

    private transient Manga _manga;
    private transient Mangareader _mangareader;

    /**
     * Get the implicit join path to the <code>public.manga</code> table.
     */
    public Manga manga() {
        if (_manga == null)
            _manga = new Manga(this, Keys.TO_READ__TO_READ_MANGA_ID_FKEY);

        return _manga;
    }

    /**
     * Get the implicit join path to the <code>public.mangareader</code> table.
     */
    public Mangareader mangareader() {
        if (_mangareader == null)
            _mangareader = new Mangareader(this, Keys.TO_READ__TO_READ_USER_ID_FKEY);

        return _mangareader;
    }

    @Override
    @NotNull
    public ToRead as(String alias) {
        return new ToRead(DSL.name(alias), this);
    }

    @Override
    @NotNull
    public ToRead as(Name alias) {
        return new ToRead(alias, this);
    }

    @Override
    @NotNull
    public ToRead as(Table<?> alias) {
        return new ToRead(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    @NotNull
    public ToRead rename(String name) {
        return new ToRead(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    @NotNull
    public ToRead rename(Name name) {
        return new ToRead(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    @NotNull
    public ToRead rename(Table<?> name) {
        return new ToRead(name.getQualifiedName(), null);
    }

    // -------------------------------------------------------------------------
    // Row2 type methods
    // -------------------------------------------------------------------------

    @Override
    @NotNull
    public Row2<Long, Long> fieldsRow() {
        return (Row2) super.fieldsRow();
    }

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Function)}.
     */
    public <U> SelectField<U> mapping(Function2<? super Long, ? super Long, ? extends U> from) {
        return convertFrom(Records.mapping(from));
    }

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Class,
     * Function)}.
     */
    public <U> SelectField<U> mapping(Class<U> toType, Function2<? super Long, ? super Long, ? extends U> from) {
        return convertFrom(toType, Records.mapping(from));
    }
}
